[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "deepecohab"
version = "0.4"
description = "EcoHab with some machine learning"
readme = "README.md"
requires-python = ">=3.13"
license = "MIT"
authors = [
    {name = "Konrad Danielewski", email = "k.danielewski@nencki.edu.pl"},
    {name = "Ula WÅ‚odkowska", email = "u.wlodkowska@nencki.edu.pl"},
]
keywords = ["ecology", "dash", "data-visualization"]
classifiers = [
    "Programming Language :: Python :: 3",
    "MIT",
    "Operating System :: OS Independent",
]

dependencies = [
    "dash",
    "dash-bootstrap-components",
    "ipykernel",
    "kaleido",
    "nbformat",
    "networkx",
    "numpy",
    "openskill",
    "plotly",
    "polars",
    "scipy",
    "toml",
    "tzlocal",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["deepecohab*"]
namespaces = true